###
GET http://localhost:5000/admins
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsInVzZXJuYW1lIjoiZ2FuamFyIiwiaWF0IjoxNzE4MjAxNTcwLCJleHAiOjE3MTgyMDE2MzB9.T8vdWcL4SNUFSsFDy7z0-xQzjAHpepy5KVyBuyvTYX8



###
POST http://localhost:5000/users
Content-Type: application/json

{
  "username":"coach justin",
  "email":"justin221@gmail.com",
  "nama_kelas":"taktik penjas",
  "password":"123456",
  "confPassword":"123456"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
  "username":"coach justin",
  "password":"123456"
}


###
GET http://localhost:5000/admin-token


###
DELETE http://localhost:5000/admin-logout